FIREBASE_WEB_API_KEY = "AIzaSyBE-3m5UMRwmwtzkgzcWo02uOVIzEu6UNc"
GOOGLE_MAPS_API_KEY = "AIzaSyD0SiBZN7Rp9Gr8v86q69iuHRVWWDyv9VQ"
OPENAI_API_KEY = "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"
CENSUS_KEY="9873cb96ddca9200a10b8c9f57c34fa09dc0ceaf"
MONGO_URI = "mongodb+srv://overlord-one:sbNciWt8sf5KUkmU@asc-fin-data.oxz1gjj.mongodb.net/?retryWrites=true&w=majority"
PINECONE_API_KEY = '5c4da4f9-8e10-426d-855c-88039d429064'
PINECONE_ENVIRONMENT = 'us-east-1-aws'
PINECONE_INDEX_NAME = "asc-demographics-embeddings"